version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth_service:
    build: ./auth_service
    ports:
      - "5001:5001"

  order_service:
    build: ./order_service
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - mongo
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - 16686:16686
        - 4317:4317
    environment:
        COLLECTOR_OTLP_ENABLED: true
volumes:
  mongo-data:
